[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci --cache .npm --prefer-offline"]

[phases.build]
cmds = ["rm -rf dist", "npm run build"]

[start]
cmd = "npx serve dist -s -l $PORT"
